### ISSUE TITLE
Unable to create constraints on a group & childrens after copy/paste from another document

### ISSUE THREAD

**Issue by EtienneServant** [matt-curtis/Fluid-for-Sketch#31] opened 2015-11-05 13:48 UTC
When I create a constraint on a group I copied from another document, every layer of this group have the same constraint.

But if I close & reopen Sketch, It works fine.

**Comment by matt-curtis** [comment] 2015-11-05 18:43
Pretty sure this is caused by #4, which is fixed in the next version

**Closed as completed by matt-curtis** 2015-11-05 18:43 UTC
Labels: bug, resolved in future release

**Comment by EtienneServant** [comment] 2015-11-05 18:44
@matt-curtis Okay thanks !
