### ISSUE TITLE
Support editing (or at least pasting) constraints to multiple selected layers

### ISSUE THREAD

**Issue by lukeadamson** [matt-curtis/Fluid-for-Sketch#42] opened 2015-11-09 23:07 UTC
It would be very nice if we could apply constraints to the set of selected layers, or at least "paste" previously copied constraints to the selected layers.

Right now it's a little tedious to set up constraints for a series of "table rows", for example, because you  have to select and set the constraints for each layer individually. Fluid doesn't complain if you select multiple layers and then try to set their constraints as one operation, but it also doesn't work.

**Comment by matt-curtis** [comment] 2015-11-09 23:35
This is a duplicate of issue #8 - this is something I'm actually working on now, it'll be out in the next release.

**Closed as completed by matt-curtis** 2015-11-09 23:35 UTC
