### ISSUE TITLE
Artboard presets at preview

### ISSUE THREAD

**Issue by edge0703** [matt-curtis/Fluid-for-Sketch#97] opened 2016-05-14 03:47 UTC
Any chance to get artboard presets at the preview? Because at the moment you can't change a custom artboard, let's say 1440x4000, to an artboard with the same height, but a different width, for example 1024. To simulate a responsive article.

So basically I can't use Constraints with my tall article page right now, correct?

**Comment by matt-curtis** [comment] 2016-05-15 13:15
At this time, no. It'll be present in the next update, though. Closed as duplicate of #72

**Closed as completed by matt-curtis** 2016-05-15 13:15 UTC

**Comment by k0mrad** [comment] 2016-07-20 22:40
Hey, just want to confirm that you are working on a way to create custom preview sizes. All of the screens for our previous project was done in 2X and we love your plugin but are hesitant to remake everything in 1x right now.

**Comment by matt-curtis** [comment] 2016-07-20 22:46
> Hey, just want to confirm that you are working on a way to create custom preview sizes.

Definitely!
